// Version information for EnergyHub
// This file is auto-generated by the versioning script
// DO NOT EDIT MANUALLY - Always syncs with package.json version
export const APP_VERSION = "1.0.8";
export const BUILD_DATE = "2025-11-05";
export const BUILD_TIME = "11:04:21";
export const GIT_COMMIT = "7c89bba";
export const GIT_BRANCH = "main";

// Version metadata
export const versionInfo = {
  version: APP_VERSION,
  buildDate: BUILD_DATE,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  fullVersion: `${APP_VERSION} (${BUILD_DATE} ${BUILD_TIME})`,
};

export default versionInfo;
