// Version information for EnergyHub
// This file is auto-generated by the versioning script
// DO NOT EDIT MANUALLY - Always syncs with package.json version
export const APP_VERSION = "1.0.3";
export const BUILD_DATE = "2025-11-03";
export const BUILD_TIME = "16:20:02";
export const GIT_COMMIT = "50414e5";
export const GIT_BRANCH = "main";

// Version metadata
export const versionInfo = {
  version: APP_VERSION,
  buildDate: BUILD_DATE,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  fullVersion: `${APP_VERSION} (${BUILD_DATE} ${BUILD_TIME})`,
};

export default versionInfo;
