#!/usr/bin/env node

/**
 * Pre-build script
 * Updates version information before building
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT_DIR = path.resolve(__dirname, '..');
const VERSION_FILE = path.join(ROOT_DIR, 'src/lib/version.ts');
const PACKAGE_JSON = path.join(ROOT_DIR, 'package.json');

function getGitInfo() {
  try {
    const commit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
    const branch = execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
    return { commit, branch };
  } catch (error) {
    return { commit: 'unknown', branch: 'unknown' };
  }
}

function getCurrentDate() {
  const now = new Date();
  const date = now.toISOString().split('T')[0];
  const time = now.toTimeString().split(' ')[0];
  return { date, time };
}

function updateVersionFile() {
  // Always read from package.json - this is the single source of truth
  const packageJson = JSON.parse(fs.readFileSync(PACKAGE_JSON, 'utf8'));
  const version = packageJson.version; // Always sync from package.json
  
  const { date, time } = getCurrentDate();
  const { commit, branch } = getGitInfo();
  
  const content = `// Version information for EnergyHub
// This file is auto-generated by the versioning script
// DO NOT EDIT MANUALLY - Always syncs with package.json version
export const APP_VERSION = "${version}";
export const BUILD_DATE = "${date}";
export const BUILD_TIME = "${time}";
export const GIT_COMMIT = "${commit}";
export const GIT_BRANCH = "${branch}";

// Version metadata
export const versionInfo = {
  version: APP_VERSION,
  buildDate: BUILD_DATE,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  fullVersion: \`\${APP_VERSION} (\${BUILD_DATE} \${BUILD_TIME})\`,
};

export default versionInfo;
`;
  
  fs.writeFileSync(VERSION_FILE, content);
  console.log(`✓ Synced version.ts from package.json: ${version} (${date} ${time})`);
}

// Run update
updateVersionFile();

