#!/usr/bin/env node

/**
 * EnergyHub Version Management Script
 * 
 * This script manages version numbers and changelog updates.
 * Usage:
 *   npm run version:patch   - Increment patch version (1.0.0 -> 1.0.1) and push
 *   npm run version:minor   - Increment minor version (1.0.0 -> 1.1.0) and push
 *   npm run version:major   - Increment major version (1.0.0 -> 2.0.0) and push
 *   npm run version:deploy  - Auto-increment patch version, update changelog, and push
 * 
 * Options:
 *   --no-push   - Skip automatic git push (for testing)
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT_DIR = path.resolve(__dirname, '..');
const PACKAGE_JSON = path.join(ROOT_DIR, 'package.json');
const VERSION_FILE = path.join(ROOT_DIR, 'src/lib/version.ts');
const CHANGELOG_FILE = path.join(ROOT_DIR, 'CHANGELOG.md');

// Color codes for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  red: '\x1b[31m',
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function getCurrentVersion() {
  const packageJson = JSON.parse(fs.readFileSync(PACKAGE_JSON, 'utf8'));
  return packageJson.version;
}

function parseVersion(version) {
  const parts = version.split('.').map(Number);
  return {
    major: parts[0],
    minor: parts[1],
    patch: parts[2],
    full: version,
  };
}

function incrementVersion(currentVersion, type) {
  const { major, minor, patch } = parseVersion(currentVersion);
  
  switch (type) {
    case 'major':
      return `${major + 1}.0.0`;
    case 'minor':
      return `${major}.${minor + 1}.0`;
    case 'patch':
      return `${major}.${minor}.${patch + 1}`;
    default:
      throw new Error(`Invalid version type: ${type}`);
  }
}

function getGitInfo() {
  try {
    const commit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
    const branch = execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
    return { commit, branch };
  } catch (error) {
    return { commit: 'unknown', branch: 'unknown' };
  }
}

function getCurrentDate() {
  const now = new Date();
  const date = now.toISOString().split('T')[0];
  const time = now.toTimeString().split(' ')[0];
  return { date, time };
}

function updatePackageJson(newVersion) {
  const packageJson = JSON.parse(fs.readFileSync(PACKAGE_JSON, 'utf8'));
  packageJson.version = newVersion;
  fs.writeFileSync(PACKAGE_JSON, JSON.stringify(packageJson, null, 2) + '\n');
  log(`✓ Updated package.json to version ${newVersion}`, 'green');
}

function updateVersionFile(newVersion) {
  // Always read from package.json to ensure sync
  const packageJson = JSON.parse(fs.readFileSync(PACKAGE_JSON, 'utf8'));
  const version = packageJson.version; // Use version from package.json
  
  const { date, time } = getCurrentDate();
  const { commit, branch } = getGitInfo();
  
  const content = `// Version information for EnergyHub
// This file is auto-generated by the versioning script
// DO NOT EDIT MANUALLY - Always syncs with package.json version
export const APP_VERSION = "${version}";
export const BUILD_DATE = "${date}";
export const BUILD_TIME = "${time}";
export const GIT_COMMIT = "${commit}";
export const GIT_BRANCH = "${branch}";

// Version metadata
export const versionInfo = {
  version: APP_VERSION,
  buildDate: BUILD_DATE,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  fullVersion: \`\${APP_VERSION} (\${BUILD_DATE} \${BUILD_TIME})\`,
};

export default versionInfo;
`;
  
  fs.writeFileSync(VERSION_FILE, content);
  log(`✓ Updated version.ts with version ${version} (synced from package.json)`, 'green');
}

function updateChangelog(newVersion, type) {
  const { date } = getCurrentDate();
  const { commit } = getGitInfo();
  
  let changelog = '';
  if (fs.existsSync(CHANGELOG_FILE)) {
    changelog = fs.readFileSync(CHANGELOG_FILE, 'utf8');
  }
  
  const versionHeader = `## [${newVersion}] - ${date}`;
  const changeType = type === 'major' ? 'MAJOR' : type === 'minor' ? 'MINOR' : 'PATCH';
  
  const newEntry = `${versionHeader}
### ${changeType}
- Auto-generated release entry
- Git commit: ${commit}
- Build date: ${date}

`;

  // Insert new entry after the first line (usually the title)
  const lines = changelog.split('\n');
  const titleLine = lines[0] || '# Changelog';
  const rest = lines.slice(1).join('\n');
  
  const updatedChangelog = `${titleLine}\n\n${newEntry}${rest}`;
  
  fs.writeFileSync(CHANGELOG_FILE, updatedChangelog);
  log(`✓ Updated CHANGELOG.md with version ${newVersion}`, 'green');
}

function promptForChanges() {
  // In non-interactive mode (CI/CD), return empty
  if (process.env.CI || !process.stdin.isTTY) {
    return [];
  }
  
  // For interactive mode, could prompt user for changes
  // For now, return empty array - changes should be added manually
  return [];
}

function getGitStatus() {
  try {
    const status = execSync('git status --porcelain', { encoding: 'utf8' });
    return status.trim();
  } catch (error) {
    return '';
  }
}

function getCurrentBranch() {
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
  } catch (error) {
    return 'main';
  }
}

function commitAndTag(newVersion, type) {
  try {
    const branch = getCurrentBranch();
    const gitStatus = getGitStatus();
    
    if (!gitStatus) {
      log('⚠️  No changes to commit', 'yellow');
      return false;
    }
    
    log('\n📝 Staging changes...', 'blue');
    execSync('git add -A', { stdio: 'inherit' });
    
    log('💾 Creating commit...', 'blue');
    const commitMessage = `chore: bump version to ${newVersion}`;
    execSync(`git commit -m "${commitMessage}"`, { stdio: 'inherit' });
    log(`✓ Committed changes`, 'green');
    
    log('🏷️  Creating tag...', 'blue');
    const tagMessage = `Release version ${newVersion}`;
    execSync(`git tag -a v${newVersion} -m "${tagMessage}"`, { stdio: 'inherit' });
    log(`✓ Created tag v${newVersion}`, 'green');
    
    return true;
  } catch (error) {
    log(`⚠️  Git operations failed: ${error.message}`, 'yellow');
    return false;
  }
}

function pushToRemote(newVersion, shouldPush) {
  if (!shouldPush) {
    log('\n⏭️  Skipping push (--no-push flag or CI detected)', 'yellow');
    return false;
  }
  
  try {
    const branch = getCurrentBranch();
    log(`\n🚀 Pushing to origin/${branch}...`, 'blue');
    
    execSync(`git push origin ${branch}`, { stdio: 'inherit' });
    log(`✓ Pushed commits to origin/${branch}`, 'green');
    
    log(`🏷️  Pushing tags...`, 'blue');
    execSync(`git push origin v${newVersion}`, { stdio: 'inherit' });
    log(`✓ Pushed tag v${newVersion}`, 'green');
    
    return true;
  } catch (error) {
    log(`⚠️  Push failed: ${error.message}`, 'yellow');
    log(`   You may need to push manually: git push origin ${getCurrentBranch()} --tags`, 'yellow');
    return false;
  }
}

function main() {
  const args = process.argv.slice(2);
  const type = args.find(arg => ['major', 'minor', 'patch'].includes(arg)) || 'patch';
  const noPush = args.includes('--no-push');
  const shouldPush = !noPush && !process.env.CI; // Auto-push unless --no-push flag or CI environment
  
  if (!['major', 'minor', 'patch'].includes(type)) {
    log('Error: Invalid version type. Use: major, minor, or patch', 'red');
    process.exit(1);
  }
  
  log('\n🚀 EnergyHub Version Manager', 'bright');
  log('=' .repeat(50), 'blue');
  
  const currentVersion = getCurrentVersion();
  log(`Current version: ${currentVersion}`, 'yellow');
  
  const newVersion = incrementVersion(currentVersion, type);
  log(`New version: ${newVersion}`, 'green');
  
  log('\nUpdating files...', 'blue');
  
  try {
    updatePackageJson(newVersion);
    // Update version.ts immediately after package.json to keep them in sync
    updateVersionFile(newVersion);
    updateChangelog(newVersion, type);
    
    log('\n✅ Version update complete!', 'green');
    
    // Commit and tag
    const committed = commitAndTag(newVersion, type);
    
    if (committed) {
      // Push if enabled
      if (shouldPush) {
        pushToRemote(newVersion, true);
        log('\n🎉 Release complete!', 'green');
        log(`   Version ${newVersion} has been pushed to origin`, 'green');
      } else {
        log(`\n📋 Next steps:`, 'bright');
        log(`1. Review and update CHANGELOG.md with actual changes`, 'yellow');
        log(`2. Push manually: git push origin ${getCurrentBranch()} --tags`, 'yellow');
      }
    } else {
      log(`\n📋 Next steps:`, 'bright');
      log(`1. Review and update CHANGELOG.md with actual changes`, 'yellow');
      log(`2. Commit changes: git add -A && git commit -m "chore: bump version to ${newVersion}"`, 'yellow');
      log(`3. Create tag: git tag -a v${newVersion} -m "Release version ${newVersion}"`, 'yellow');
      log(`4. Push: git push origin ${getCurrentBranch()} --tags`, 'yellow');
    }
  } catch (error) {
    log(`\n❌ Error: ${error.message}`, 'red');
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  main();
}

module.exports = {
  getCurrentVersion,
  incrementVersion,
  updatePackageJson,
  updateVersionFile,
  updateChangelog,
};

